### ISSUE TITLE
Not work on safari , ios16, cause the lookbehind regex

### ISSUE THREAD

**Issue by xiongtoto0526** [aarkue/tiptap-math-extension#10]
- Problem
src/latex-evaluation/evaluate-expression.ts, 
line50:   const r = new RegExp("(^|(?<=[^a-zA-Z]))" + regexSafeAlias + "($|(?=[^a-zA-Z]))", "g");
Here ,the '?<=' result a lookbehind regex usage, which is not support on safari  ios16.4 or  lower version.

- support table
https://caniuse.com/js-regexp-lookbehind

- Workaround (maybe)
https://prathamesh.tech/2023/01/17/workaround-for-lookbehind-regex-in-safari/

- Tool
below is an online convert tool,
https://regexr.com/6qq8k

btw, this extension is awesome, respect a quick fix for the problem , and npm deploy  , thanks ~

**Comment by aarkue** [comment]
Hi, Thanks for reporting this issue! So far, I never experienced any problems as the support for lookbehind appears to be rather good (almost 95%).
I am also open to increasing the compatibility further, so we could look into either replacing the lookbehind or using a different regex (maybe with fewer safeguards) for browsers which do not support it.

To clarify: Do you only run into issues with the expression evaluation feature (i.e., the regex from `evaluate-expression.ts`? I noticed that the regular expression for matching dollar-sign delimited math (e.g., `$x_1 + x_2$`) also uses _negative_ lookbehind (`?<!\$)...`). There, you could also do a workaround manually, as this extension allows specifying a regex manually through the options (see the options for `delimiters`).


Cheers,
Aaron

**Comment by xiongtoto0526** [comment]
> Hi, Thanks for reporting this issue! So far, I never experienced any problems as the support for lookbehind appears to be rather good (almost 95%). I am also open to increasing the compatibility further, so we could look into either replacing the lookbehind or using a different regex (maybe with fewer safeguards) for browsers which do not support it.
> 
> To clarify: Do you only run into issues with the expression evaluation feature (i.e., the regex from `evaluate-expression.ts`? I noticed that the regular expression for matching dollar-sign delimited math (e.g., `$x_1 + x_2$`) also uses _negative_ lookbehind (`?<!\$)...`). There, you could also do a workaround manually, as this extension allows specifying a regex manually through the options (see the options for `delimiters`).
> 
> Cheers, Aaron

I just run the example , and it breaked at  addInputRule ( source code related to getRegexFromOptions fn)..., as you mentioned above ,  I change the delimiters configuration , and it works .... so,  here is my conf: 
``` 
 MathExtension.configure({
    evaluation: false,  // this must be false, or it may cause a new lookbehind regex in evaluate-expression.ts , as I mentioned above 
     katexOptions: { macros: { '\\B': '\\mathbb{B}' } },
     delimiters: {
       inlineRegex: String.raw`\$(?!\$)([^$\\\s\(\[\]\",]+(?:[^$\\\s\(\[\]\",\\]*[^\\\s\(\[\]\",])?)\$`,  // rewrite the default rule
       blockRegex: String.raw`\$\$(?!\s)((?:[^\\]|\\.)*?)\$\$`,  // rewrite the default rule
     },
   }),
   }, ```  , hope to help someone .

**Comment by aarkue** [comment]
Great to hear it's working with the workaround. Maybe I will add a notice to the readme regarding the browser comparability for others running into the same issue.

Cheers!
