### ISSUE TITLE
the latex is not rendering properly

### ISSUE THREAD

**Issue by anishjoshi1999** [aarkue/tiptap-math-extension#11]
![image](https://github.com/user-attachments/assets/293c3ef6-9964-4243-b592-a452f3b8fc90)
When I type "$$\sum_{i=0}^n i^2$$" in the text editor, it still shows some unwanted text.

Here is the code:

import React, { useEffect } from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import EditorToolbar from "./EditorToolbar";
import Blockquote from "@tiptap/extension-blockquote";
import Image from "@tiptap/extension-image";
import Placeholder from "@tiptap/extension-placeholder";
import MathExtension from "@aarkue/tiptap-math-extension";

const WYSIWYGEditor = ({ index, question, onQuestionChange }) => {
  // Initialize the Tiptap editor
  const editor = useEditor({
    extensions: [
      StarterKit,
      Blockquote,
      Image,
      Placeholder.configure({
        placeholder:"Start typing your question here...",
        emptyNodeClass:
          'first:before:text-gray-400 first:before:float-left first:before:content-[attr(data-placeholder)] first:before:pointer-events-none',
      }),
      MathExtension.configure({ evaluation: false, katexOptions: { macros: { "\\B": "\\mathbb{B}" } }, delimiters: "dollar" }),
    ],
    content: typeof window !== "undefined" ? question.question : "", // Ensure content is loaded only on the client
    editorProps: {
      attributes: {
        class:
          "prose prose-sm sm:prose lg:prose-lg xl:prose-2xl mx-auto focus:outline-none min-h-[200px] p-4",
      },
    },
    immediatelyRender: false, // Prevent rendering immediately on the server
  });

  // Effect to listen for updates in the editor content
  useEffect(() => {
    if (editor) {
      const handleEditorChange = () => {
        onQuestionChange(index, "question", editor.getHTML());
      };

      // Listen for updates from the editor
      editor.on("update", handleEditorChange);

      // Clean up the listener when the component unmounts
      return () => {
        editor.off("update", handleEditorChange);
      };
    }
  }, [editor, index, onQuestionChange]);

  if (!editor) {
    return null;
  }

  return (
    <div className="w-full max-w-4xl mx-auto">
      <div className="border rounded-lg shadow-sm bg-white">
        <EditorToolbar editor={editor} />
        <div className="border-t">
          <EditorContent editor={editor} />
        </div>
      </div>
    </div>
  );
};

export default WYSIWYGEditor;

**Comment by aarkue** [comment]
Hi, thanks for reaching out.

I believe the issues might be that the KaTeX CSS is not included in the webpage.

From the README:
To correctly render the LaTeX expressions, you will also need to include the KaTeX CSS. If you are using vite you can use import "katex/dist/katex.min.css"; in the component which renders the tiptap editor.


Let me know if this works or if you still run into issues!

Cheers
