### ISSUE TITLE
LaTeX is rendering twice (Tiptap Vue)

### ISSUE THREAD

**Issue by codewriter3000** [aarkue/tiptap-math-extension#3]
When I type in $x + 4 = 7$ into my Tiptap editor, I get something like this:
![image](https://github.com/aarkue/tiptap-math-extension/assets/58712923/bf5bbf66-56c8-4292-80a5-bcee0ea60c5c)

I'm using Astro and this is a Vue component

```
Astro                    v4.4.9
Node                     v20.11.0
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/vue
                         astro-icon
```

**Comment by aarkue** [comment]
Hi, Thanks for raising this issue!

This looks like missing KaTeX CSS.
Try including something like `import "katex/dist/katex.min.css";` (if you are using Vite) in the file that creates the TipTap editor.
Note, that you might need to install the KaTeX  `npm i katex` from https://www.npmjs.com/package/katex to make sure the CSS is available and can be correctly bundled.


There are also other ways to load the KaTeX CSS, see https://katex.org/docs/browser.

I should probably include a mention on how to include the KaTeX CSS in the README. Will do that soon!

Let me know if that fixed your issue.
